export const inputTypes = {
  TEXT: "text",
  CHECKBOX: "checkbox",
  RADIO: "radio",
  EMAIL: "email",
  PASSWORD: "password",
  TEL: "tel",
  BUTTON: "button"
  //  : '',
  //  : '',
  //  : '',
  //  : '',
  //  : '',
  //  : '',
  //  : '',
  //  : '',
  //  : '',
  //  : '',
  //  : '',
  //  : '',
};
